# Updates the Gradle Cache when Necessary (from https://github.com/GregTechCEu/GregTech/blob/master/.github/workflows/update_gradle_cache.yml)
name: Update Gradle Cache

on:
  push:
    branches:
      - master
    paths: ['gradle/**', '**.gradle', 'gradle.properties', 'gradlew**', 'src/main/resources/*_at.cfg']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-cache:
    name: Update Grade Cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Build
        uses: ./.github/actions/build_setup

      - name: Build Project with Gradle
        run: ./gradlew assemble --warning-mode all --build-cache
